<template>
  <div>
    <LandingComponentsSectionsBannerSection/>
    <LandingComponentsSectionsInfoSection/>
    <LandingComponentsSectionsCarouselSection/>
    <LandingComponentsSectionsArtistsSection/>
    <LandingComponentsSectionsEventsSection/>
    <LandingComponentsSectionsActivitiesSection/>
    <LandingComponentsSectionsBannerSocialSection/>
    <LandingComponentsSectionsSponsorSection/>
  </div>
</template>
